### ISSUE TITLE
Image could be malloc'd instead of GC allocated

### ISSUE THREAD

**Issue by p0nce** [CyberShadow/ae#14]
I'm a bit wary of GC scan time for large `ae.utils.graphics.image.Image`.
Since image data is not supposed to be pointers, perhaps we could instead use malloc/free?
https://github.com/CyberShadow/ae/blob/master/utils/graphics/image.d#L75

**Comment by CyberShadow** [comment]
The GC already does not scan memory areas which do not contain pointers.
