### ISSUE TITLE
Another 8-byte real issue

### ISSUE THREAD

**Issue by p0nce** [CyberShadow/ae#16]
https://github.com/CyberShadow/ae/blob/master/utils/meta/package.d#L437

```d
static assert(valueBits!real == 64);
```
This isn't true where `real` is the same as `double`.

Suggested change:
```d
static assert(valueBits!double == 53);
```

**Comment by CyberShadow** [comment]
6400efbd9bcc8f631b4a48efa9367521a58d8346
