### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by dancingspider** [CyberShadow/ae#26]
E:\gh\code>rdmd ae/demo/pewpew/pewpew
ae\utils\alloc.d(153): Error: static assert  "Your compiler doesn't support fiel
d alias template parameter binding, which is required for ae.utils.alloc."
Failed: ["dmd", "-v", "-o-", "ae/demo/pewpew/pewpew.d", "-Iae/demo/pewpew"]

**Comment by CyberShadow** [comment]
Should be fixed in ae778c33955111a5626c905be6f79cf146043864, thanks.
