### ISSUE TITLE
timeouts in CI suite

### ISSUE THREAD

**Issue by MartinNowak** [CyberShadow/ae#30]
Regularly seeing timeouts like this one in the testsuite https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/master/363/pipeline/#step-371-log-28.
In fact the tested server wasn't reachable right now for a short time.
Any chance this could be changed to a local test like the one in std.net.curl?
https://github.com/dlang/phobos/pull/3576

```
Testing AENetwork
 - getFile
object.Exception@sys/net/ae.d(33): Time-out
----------------
sys/net/ae.d:33 pure @safe void ae.sys.net.ae.AENetwork.getData(immutable(char)[]).__lambda3(immutable(char)[]) [0x8be59b]
net/http/client.d:326 void ae.net.http.client.httpRequest(ae.net.http.common.HttpRequest, void delegate(ae.sys.data.Data), void delegate(immutable(char)[]), int).responseHandler(ae.net.http.common.HttpResponse, immutable(char)[]) [0x8509ab]
net/http/client.d:199 void ae.net.http.client.HttpClient.processResponse(immutable(char)[]) [0x85032a]
net/http/client.d:208 void ae.net.http.client.HttpClient.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x85037e]
net/asockets.d:1368 void ae.net.asockets.ConnectionAdapter.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x783b5a]
net/asockets.d:1557 void ae.net.asockets.TimeoutAdapter.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x784525]
net/asockets.d:944 void ae.net.asockets.StreamConnection.disconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x782711]
net/asockets.d:1350 void ae.net.asockets.ConnectionAdapter.disconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x783a33]
net/asockets.d:1583 void ae.net.asockets.TimeoutAdapter.onTask_Idle(ae.sys.timing.Timer, ae.sys.timing.TimerTask) [0x784650]
sys/timing.d:212 bool ae.sys.timing.Timer.prod() [0x8c7947]
net/asockets.d:417 void ae.net.asockets.SocketManager.loop() [0x781334]
sys/net/ae.d:36 ae.sys.data.Data ae.sys.net.ae.AENetwork.getData(immutable(char)[]) [0x8be41b]
sys/net/ae.d:49 void[] ae.sys.net.ae.AENetwork.getFile(immutable(char)[]) [0x8be68b]
sys/net/test.d:34 void ae.sys.net.test.test!("ae", "AENetwork").test() [0x8c2526]
sys/net/test.d:68 void ae.sys.net.test.__unittestL66_144() [0x8c24a0]
```

**Comment by CyberShadow** [comment]
Sorry about that. Right now the respective server is overloaded so some requests may time out. I'm working on that right now.

A local test server shouldn't be too difficult to do for HTTP, but HTTPS is more tricky. However, I think it would be better to have a way to disable network tests when running on the project tester altogether. That would be a more general solution that would also apply to situations where it's infeasible to make the tests completely encapsulated. Is there an environment variable I could check for that would disable these tests?

**Comment by CyberShadow** [comment]
> Is there an environment variable or such I could check for that would disable these tests?

Please get back to me on that, but for the moment I unconditionally disabled the network tests and pushed a new tag to avoid any problems with the project tester ASAP.

**Comment by wilzbach** [comment]
>  Is there an environment variable or such I could check for that would disable these tests?

http://www.scmgalaxy.com/tutorials/environment-variables-and-properties-defined-in-jenkins/

`JENKINS_URL` unique enough for you?

**Comment by CyberShadow** [comment]
> JENKINS_URL unique enough for you?

If htat's actually set on our instance, sure. Why the snark though :)

**Comment by wilzbach** [comment]
> If htat's actually set on our instance, sure.

Quickly checked:

![image](https://user-images.githubusercontent.com/4370550/35634350-cb969bd4-06ab-11e8-87c5-d366303a3f15.png)

with https://github.com/dlang/ci/pull/153

> Why the snark though

Oh it was intended to be negative. I just browsed the list and searched for the most unique environment variable.

**Comment by CyberShadow** [comment]
> Quickly checked:

Thanks!

> Oh it was intended to be negative.

Well, I guess I deserved that, with everyone else doing all the work to fix my broken tests. :)

Anyway, I think it should be OK to revert https://github.com/dlang/ci/pull/152 now.
