### ISSUE TITLE
compiling with ae - unresolved externals

### ISSUE THREAD

**Issue by msimic** [CyberShadow/ae#38]
have trouble compiling when including ae...

what do i need to link?

I use Visual Studio 2017 with a Plugin for D and dmd2.

Have followed this setup guide and have the win32 folder:
http://worms2d.info/4/Development_setup

> 1>------ Build started: Project: extractor, Configuration: Debug Win32 ------
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "ae.sys.windows.window.WindowIterator ae.sys.windows.window.windowIterator(immutable(char)[], immutable(char)[], void*)" (__D2ae3sys7windows6window14windowIteratorFAyaQdPvZSQBwQBwQBvQBq14WindowIterator) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "const @property bool ae.sys.windows.window.WindowIterator.empty()" (__D2ae3sys7windows6window14WindowIterator5emptyMxFNdZb) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "const @property void* ae.sys.windows.window.WindowIterator.front()" (__D2ae3sys7windows6window14WindowIterator5frontMxFNdZPv) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "immutable(char)[] ae.sys.windows.window.windowStringQuery!(GetWindowTextW).windowStringQuery(void*)" (__D2ae3sys7windows6window__T17windowStringQueryX14GetWindowTextWZQBlFPvZAya) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "void ae.sys.windows.window.WindowIterator.popFront()" (__D2ae3sys7windows6window14WindowIterator8popFrontMFZv) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "int win32.commctrl.ListView_GetItemCount(void*)" (__D5win328commctrl21ListView_GetItemCountFPvZi) referenced in function __Dmain
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "int win32.commctrl.ListView_GetItem(void*, win32.commctrl.LVITEMA*)" (__D5win328commctrl16ListView_GetItemFPvPSQBmQBj7LVITEMAZi) referenced in function "immutable(char)[] extractor.main().getListItem(uint, uint)" (__D9extractor4mainFZ11getListItemMFkkZAya)
1>dcompile_extractor.obj : error LNK2001: unresolved external symbol "void ae.sys.windows.process.ToolhelpSnapshotImpl.__dtor()" (__D2ae3sys7windows7process20ToolhelpSnapshotImpl6__dtorMFZv)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "ae.sys.windows.exception.WindowsException.__Class" (__D2ae3sys7windows9exception16WindowsException7__ClassZ) referenced in function "void* ae.sys.windows.exception.wenforce!(void*).wenforce(void*, immutable(char)[])" (__D2ae3sys7windows9exception__T8wenforceTPvZQnFQgAyaZQm)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "ae.sys.windows.exception.WindowsException ae.sys.windows.exception.WindowsException.__ctor(uint, immutable(char)[])" (__D2ae3sys7windows9exception16WindowsException6__ctorMFkAyaZCQCgQCgQCfQCaQBt) referenced in function "void* ae.sys.windows.exception.wenforce!(void*).wenforce(void*, immutable(char)[])" (__D2ae3sys7windows9exception__T8wenforceTPvZQnFQgAyaZQm)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "void ae.sys.windows.process.readProcessMemory(void*, ubyte*, void[])" (__D2ae3sys7windows7process17readProcessMemoryFPvPhAvZv) referenced in function "void ae.sys.windows.process.RemoteProcessVarImpl!(char[1024]).RemoteProcessVarImpl.read()" (__D2ae3sys7windows7process__T20RemoteProcessVarImplTG1024aZQBe4readMFZv)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "void ae.sys.windows.process.writeProcessMemory(void*, ubyte*, const(void)[])" (__D2ae3sys7windows7process18writeProcessMemoryFPvPhAxvZv) referenced in function "void ae.sys.windows.process.RemoteProcessVarImpl!(char[1024]).RemoteProcessVarImpl.write()" (__D2ae3sys7windows7process__T20RemoteProcessVarImplTG1024aZQBe5writeMFZv)
1>dcompile_extractor.obj : error LNK2001: unresolved external symbol "void ae.sys.windows.process.CreatedProcessImpl.__dtor()" (__D2ae3sys7windows7process18CreatedProcessImpl6__dtorMFZv)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "const pure nothrow @property @nogc @safe bool std.typecons.RefCounted!(ae.sys.windows.process.ToolhelpSnapshotImpl, 1).RefCounted.RefCountedStore.isInitialized()" (__D3std8typecons__T10RefCountedTS2ae3sys7windows7process20ToolhelpSnapshotImplVEQCzQCy24RefCountedAutoInitializei1ZQDs15RefCountedStore13isInitializedMxFNaNbNdNiNfZb) referenced in function "pure nothrow @nogc @safe void std.typecons.RefCounted!(ae.sys.windows.process.ToolhelpSnapshotImpl, 1).RefCounted.__postblit()" (__D3std8typecons__T10RefCountedTS2ae3sys7windows7process20ToolhelpSnapshotImplVEQCzQCy24RefCountedAutoInitializei1ZQDs10__postblitMFNaNbNiNfZv)
1>dcompile_extractor.obj : error LNK2019: unresolved external symbol "void object.destroy!(ae.sys.windows.process.ToolhelpSnapshotImpl).destroy(ref ae.sys.windows.process.ToolhelpSnapshotImpl)" (__D6object__T7destroyTS2ae3sys7windows7process20ToolhelpSnapshotImplZQCeFKQCaZv) referenced in function "void std.typecons.RefCounted!(ae.sys.windows.process.ToolhelpSnapshotImpl, 1).RefCounted.__dtor()" (__D3std8typecons__T10RefCountedTS2ae3sys7windows7process20ToolhelpSnapshotImplVEQCzQCy24RefCountedAutoInitializei1ZQDs6__dtorMFZv)
1>C:\Users\Mars\source\repos\extractor\Debug\extractor.exe : fatal error LNK1120: 15 unresolved externals
1>Done building project "extractor.vcxproj" -- FAILED.

**Comment by CyberShadow** [comment]
Sorry, I don't know. Visual Studio is not a supported build system.

If it builds from the command line (e.g. with Dub) but not in Visual Studio, it is probably a bug in the D plugin you're using. Please file bugs to their bugtracker, not here.
