### ISSUE TITLE
Update OpenSSL

### ISSUE THREAD

**Issue by nu8** [CyberShadow/ae#47]
If I try to compile a project using this:

~~~
import ae.net.ssl.openssl;
~~~

I get this:

~~~
lld-link: error: could not open 'ssleay32.lib': no such file or directory
lld-link: error: could not open 'libeay32.lib': no such file or directory
~~~

https://github.com/CyberShadow/ae/blob/58f19c56dc7f9f2ec690d566d76a37731f3d29da/net/ssl/openssl.d#L36-L48

the thing is, OpenSSL hasnt used those filenames since OpenSSL 1.1.0 (2016):

https://stackoverflow.com/a/55477713

at any rate, I tried the files from here, with renaming:

https://packages.msys2.org/package/mingw-w64-x86_64-openssl

but as expected, not work because of API differences:

~~~
lld-link: error: undefined symbol: SSL_load_error_strings
>>> referenced by
>>> C:\Users\Steven\AppData\Local\dub\packages\ae-0.0.2782\ae\net\ssl\openssl.d:91
~~~

**Comment by nu8** [comment]
For my future self: here is working version with HTTP:

~~~
Add dependency (leave empty to skip) []: ae
Adding dependency ae ~>0.0.2782
~~~

~~~d
import ae.net.asockets;
import ae.net.http.client;
import std.stdio;

void main() {
   Data result;
   httpGet(
      "http://speedtest.lax.hivelocity.net",
      (Data data) { result = data; },
      (string error) { throw new Exception(error); }
   );
   socketManager.loop();
   write(cast(char[])result.contents);
}
~~~

and failed version with HTTPS:

~~~
Add dependency (leave empty to skip) []: ae:openssl
Adding dependency ae:openssl ~>0.0.2782
~~~

program is same, just change link to HTTPS.

**Comment by CyberShadow** [comment]
> the thing is, OpenSSL hasnt used those filenames since OpenSSL 1.1.0 (2016):

Not as far as I can see.

How are you building OpenSSL? Or, if you're using a prebuilt version, which build are you using? OpenSSL themselves do not distribute Windows binaries.

> but as expected, not work because of API differences:

`ae` should support 1.0.0 and 1.1.0. It selects the API version to use depending on what version of D bindings you have installed.

What version of D bindings do you have installed?

**Comment by nu8** [comment]
> > the thing is, OpenSSL hasnt used those filenames since OpenSSL 1.1.0 (2016):
> 
> Not as far as I can see.

Did you see the link I put?

https://stackoverflow.com/a/55477713

also see this one:

https://packages.msys2.org/package/mingw-w64-x86_64-openssl

shows these files:

~~~
/mingw64/lib/libcrypto.a
/mingw64/lib/libssl.a
~~~

> How are you building OpenSSL?

Not building, just using the above files.

> What version of D bindings do you have installed?

I dont know if I have that installed, and if I do have it installed, I dont know
what version.

**Comment by CyberShadow** [comment]
> Did you see the link I put?

Yes, it doesn't answer the question either...

> Not building, just using the above files.

OK, so are you trying to link against the MinGW version? Can you describe the build process you're using to do that?

> I dont know if I have that installed, and if I do have it installed, I dont know
> what version.

You wouldn't get to the link step if you didn't have them installed.

As a minimum, you could add something like `pragma(msg, isOpenSSL11 ? "Using OpenSSL 1.1 or newer" : "Using OpenSSL 1.0 or older");` to openssl.d to test.

**Comment by nu8** [comment]
> > Did you see the link I put?
> 
> Yes, it doesn't answer the question either...

Again, since OpenSSL 1.1.0, these files *are not* named the same as they were
before. That can be shown in these links:

- https://curl.haxx.se/windows/dl-7.72.0_5/openssl-1.1.1h_5-win64-mingw.zip
- https://en.wikibooks.org/wiki/OpenSSL
- https://packages.msys2.org/package/mingw-w64-x86_64-openssl
- https://stackoverflow.com/a/55477713
- https://wiki.openssl.org/index.php/Libcrypto_API

> OK, so are you trying to link against the MinGW version? Can you describe the
> build process you're using to do that?

Normally I would rename like this:

~~~
libcrypto.a => crypto.lib
libssl.a => ssl.lib
~~~

but in this case I did:

~~~
libcrypto.a => libeay32.lib
libssl.a => ssleay32.lib
~~~

**Comment by CyberShadow** [comment]
> Again, since OpenSSL 1.1.0, these files _are not_ named the same as they were
> before. That can be shown in these links:

As far as I can see, none of these pages describe a change in library file names.

I think you are confusing the standard file names that the project uses when built from source on POSIX systems, with a change in file names of a certain third-party binary OpenSSL build for Windows, but you're not telling me which.

> Normally I would rename like this:

I wouldn't think this would work, because of the libc differences.

Are you sure this used to work to link these libraries with D programs with older OpenSSL versions?

**Comment by nu8** [comment]
> As far as I can see, none of these pages describe a change in library file
> names.

https://github.com/openssl/openssl/commit/6928b617

Happy?

**Comment by CyberShadow** [comment]
> https://github.com/openssl/openssl/commit/6928b617

Good to have a source reference. And, do you know how this change propagated to your build of OpenSSL?

I don't think I ever tested ae with a MinGW build of OpenSSL. I see from its package description that it at least has some dependencies which one might think would make use outside of the MinGW toolchain onerous. Also, one would think that MinGW would follow POSIX naming conventions, so it wouldn't be affected by the change you linked.

> Happy?

No. Why would I be? You have filed an incomplete bug report with a lot of missing information that I have to guess or ask, and in my attempt at figuring out the missing pieces, you're answering half of my questions and being rude to me the entire time.

**Comment by nu8** [comment]
> No. Why would I be? You have filed an incomplete bug report with a lot of
> missing information that I have to guess or ask, and in my attempt at
> figuring out the missing pieces, you're answering half of my questions and
> being rude to me the entire time.

I you want to close or walk away from this issue, thats your business. But I
have now proved that a library rename happend (years ago). So if you want to
keep stuck at the old version, thats your decision.

**Comment by CyberShadow** [comment]
> I you want to close or walk away from this issue, thats your business.

I may do so if you continue being rude :)

> But I
> have now proved that a library rename happened (years ago). So if you want to
> keep stuck at the old version, thats your decision.

The file name update is easy to fix, but I understand that you are also seeing a link error, and I need more information to understand that problem before I can fix anything.

**Comment by nu8** [comment]
I dont know what else you need. This is the entire process I took. Download
this:

https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-openssl-1.1.1.h-1-any.pkg.tar.zst

Extract these files and rename:

~~~
mingw64\lib\libcrypto.a => libeay32.lib
mingw64\lib\libssl.a => ssleay32.lib
~~~

Create project:

~~~
PS D:\Desktop\etc> dub init
Package recipe format (sdl/json) [json]:
Name [etc]:
Description [A minimal D application.]:
Author name [Steven]:
License [proprietary]:
Copyright string [Copyright © 2020, Steven]:
Add dependency (leave empty to skip) []: ae:openssl
Adding dependency ae:openssl ~>0.0.2782
Add dependency (leave empty to skip) []:
Successfully created an empty project in 'D:\Desktop\etc'.
Package successfully created in .
~~~

Then try to build:

~~~
PS D:\Desktop\etc> dub.exe build
Performing "debug" build using C:\ldc2\bin\ldc2.exe for x86_64.
etc ~master: building configuration "application"...
Linking...
lld-link: error: undefined symbol: SSL_load_error_strings
>>> referenced by C:\Users\Steven\AppData\Local\dub\packages\ae-0.0.2782\ae\net\ssl\openssl.d:91
>>> .dub\build\application-debug-windows-x86_64-ldc_2093-DE23EF5E45555A206FD50647150168E3\etc.obj:(_D2ae3net3ssl7openssl24_sharedStaticCtor_L89_C1FZv)
~~~

**Comment by CyberShadow** [comment]
> I dont know what else you need.

That's exactly what is missing. Full steps to reproduce are in general useful to include in any bug report. I also now see you're using LDC and targeting x86_64 (which wasn't useful for this particular problem, but does help a lot in diagnosing linker issues in general).

So, the link error does happen because Dub is selecting the 1.0 version of the D OpenSSL bindings. The reason for that is that ae's `dub.sdl` supports only OpenSSL 1.0 at the moment. In turn, the reason for that is because of a grievous design error in Dub. This error affects many projects, and is documented in its FAQ: https://github.com/dlang/dub/wiki/FAQ

In light of this limitation, ae's `dub.sdl` must make the choice whether to support either OpenSSL 1.0 or 1.1. The reason why it stuck to 1.0 for so long is that there are still LTS distributions where this is the only packaged version of OpenSSL. On the other hand, newer versions will generally provide 1.1+ as the default OpenSSL version, and 1.0 as an additional package for backwards compatibility with old applications that have not yet migrated to the 1.0 API. As such, the choice to support 1.0 allows maximizing compatibility across platforms.

I have an idea for how to address this, which I'm going to try now. As for immediate workarounds, those would be to build using a different build tool and set up dependencies manually, or of course link against OpenSSL 1.0.

As an aside, unless you have a technical reason to do so (such as using new functionality), I don't think there is yet a strong reason to migrate to 1.1. 1.0 seems to be still supported upstream, with the latest release being less than a year ago.

**Comment by CyberShadow** [comment]
And as another aside... I have some work-in-progress support for Botan in [the `botan` branch](https://github.com/CyberShadow/ae/commits/botan), though I've encountered [quite a few obstacles](https://github.com/etcimon/botan/pull/55) in trying to actually put it to use.

**Comment by CyberShadow** [comment]
> In turn, the reason for that is because of a grievous design error in Dub. This error affects many projects, and is documented in its FAQ: https://github.com/dlang/dub/wiki/FAQ

Filed a Dub issue: https://github.com/dlang/dub/issues/2023

**Comment by nu8** [comment]
> As an aside, unless you have a technical reason to do so (such as using new
> functionality), I don't think there is yet a strong reason to migrate to 1.1.
> 1.0 seems to be still supported upstream, with the latest release being less
> than a year ago.

I think 1.1 makes more sense in the current day. OpenSSL 3 is already being
developed:

https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-alpha6

> And as another aside... I have some work-in-progress support for Botan in
> [the `botan` branch](https://github.com/CyberShadow/ae/commits/botan), though
> I've encountered [quite a few
> obstacles](https://github.com/etcimon/botan/pull/55) in trying to actually
> put it to use.

All I really want is a simple package to do HTTPS requests. I am trying to
avoid `std.net.curl` if possible. DMD only ships a shared cURL library. LDC
ships both a shared and static library, but only been one release of the static
library, not sure if they will keep it up to date:

https://github.com/ldc-developers/mingw-w64-libs/releases

and the build process for static cURL library is painful:

https://github.com/ldc-developers/ldc/issues/3376

so if AE can work as a simple HTTPS client, or if you know another option, then
I am interested.

**Comment by CyberShadow** [comment]
I pushed some commits here:
https://github.com/CyberShadow/ae/commits/next
I think these should address the pertinent problems, though I haven't tested them on Windows. Can you check if they improve things on your end?

**Comment by CyberShadow** [comment]
In particular note the documentation added in 588dc92203884b6dc6d6f93ddee02497fce619b9 which describes how to select which version of OpenSSL to use with ae.

> All I really want is a simple package to do HTTPS requests.

For cross-platform use, for this purpose I personally would choose cURL. The advantage is that it takes care of the OpenSSL ABI pain, and libcurl itself has a stable ABI, so you don't have the insanity we have here with dancing around OpenSSL's rampant breakages.

But if you only want to target Windows, then I would recommend not using OpenSSL or cURL at all, and instead using WinINet. ae has bindings for it in `ae.sys.net.wininet`. It is part of a package which wraps different network APIs, so the same interface can also be used for cURL and `ae.net` + OpenSSL.

**Comment by nu8** [comment]
Thanks for all the work, but I dont know how to utilize anything of what youve
said.

I dont know how to make Dub use Next instead of Master or Release version.

I dont know how to make Dub use WinInet instead of OpenSSL.

If you have advice on how to accomplish those, I can give it a try.

**Comment by CyberShadow** [comment]
> I dont know how to make Dub use Next instead of Master or Release version.

Clone this repository to your PC and check out the `next` branch. Then, use `dub add-local` to register `ae` as a local package, so Dub uses it for building instead of the version in the official repository.

> I dont know how to make Dub use WinInet instead of OpenSSL.

If you want to use ae's WinINet wrapper, import `ae.sys.net` in your project, and add `ae:sys-net-wininet` as a dependency in your project. The basic API is `net.getFile("https://example.com/...")`, for more details see `sys/net/package.d` and `sys/net/test.d`.

**Comment by nu8** [comment]
Doesnt work:

~~~
PS D:\Desktop\etc> git clone git://github.com/CyberShadow/ae
PS D:\Desktop\etc> cd ae
PS D:\Desktop\etc\ae> git checkout next
PS D:\Desktop\etc\ae> cd ..
PS D:\Desktop\etc> dub add-local ae
Registered package: ae (version: 0.0.2782+commit.42.g070116a)
PS D:\Desktop\etc> dub init
Package recipe format (sdl/json) [json]:
Name [etc]:
Description [A minimal D application.]:
Author name [Steven]:
License [proprietary]:
Copyright string [Copyright © 2020, Steven]:
Add dependency (leave empty to skip) []: ae:openssl
Adding dependency ae:openssl ~>0.0.2782
Add dependency (leave empty to skip) []:
Successfully created an empty project in 'D:\Desktop\etc'.
Package successfully created in .
PS D:\Desktop\etc> dub build
Performing "debug" build using C:\ldc2\bin\ldc2.exe for x86_64.
etc ~master: building configuration "application"...
Linking...
lld-link: error: undefined symbol: OPENSSL_init_ssl
>>> referenced by D:\Desktop\etc\ae\net\ssl\openssl.d:106
~~~

**Comment by CyberShadow** [comment]
> In particular note the documentation added in [588dc92](https://github.com/CyberShadow/ae/commit/588dc92203884b6dc6d6f93ddee02497fce619b9) which describes how to select which version of OpenSSL to use with ae.

Please see the above.

**Comment by nu8** [comment]
I read that, sorry but as I said before I have no idea what that stuff means. I dont know how to translate what it on that page into commands to put into the terminal.

**Comment by CyberShadow** [comment]
Those are dub.sdl entries, so you would copy them to your dub.sdl file. If you use JSON, you would have to translate them to JSON syntax. You can look at https://dub.pm/package-format-json and https://dub.pm/package-format-sdl side-by-side to see the differences.

**Comment by nu8** [comment]
why cant I just use `dub init` or `dub add` or something?

**Comment by CyberShadow** [comment]
I don't think dub exposes all such configuration editing actions as command-line actions.

**Comment by nu8** [comment]
~~~
PS D:\Desktop\etc> dub build
Invalid SemVer format: ...
~~~

**Comment by CyberShadow** [comment]
Instead of "..." you need to put the version of ae you're using (whatever's already in your Dub configuration, probably `0.0.2782`).

**Comment by nu8** [comment]
ok I think I figured it out - I got rid of the OpenSSL errors, but now have
this:

~~~
lld-link: error: undefined symbol: __mingw_vsprintf
>>> referenced by ssl.lib(ssl_lib.o):(sprintf.constprop.0)
>>> referenced by crypto.lib(dso_win32.o):(sprintf)
~~~

If I remember right, this can be fixed by linking in `ucrtbase.lib`, but I dont
know how to do that with Dub.

**Comment by CyberShadow** [comment]
Yeah, this is what I meant by libc differences.

I think you can add a `.lib` file to your Dub configuration like: `libs ":ucrtbase.lib"` (maybe might not need the : on Windows).

**Comment by nu8** [comment]
Ok, I got it building with HTTPS by adding these:

~~~d
// part 1
libs "mincore" // from MSYS2
libs "msvcrt" // from MSYS2
libs "ucrtbase" // from LDC
// part 2
libs "mingwex" // from MSYS2
~~~

note the order is important. Also LDC did not offer most of those, so I had to
copy them from MSYS2.

**Comment by CyberShadow** [comment]
Great. Does it run?

And any luck with wininet?

**Comment by nu8** [comment]
I am able to make a request to https://speedtest.lax.hivelocity.net and https://lobste.rs, so looks all good - I think I should try WinInet though, probably much easier in the long run. However its late, gonna get some sleep.

**Comment by nu8** [comment]
Wow, WinInet is much easier!

I just did `dub init` with `ae:sys-net-wininet`, then create a file:

~~~d
import ae.sys.net, std.stdio;

void main() {
   auto s = "https://speedtest.lax.hivelocity.net";
   auto y = net.getFile(s);
   write(cast(char[])y);
}
~~~

and `dub build`, and thats it! Works even with HTTPS. Thanks!

**Comment by CyberShadow** [comment]
Alright, thanks for the feedback :)

I pushed the new commits to `master` and tagged `v0.0.2824`, so that the OpenSSL changes can be used without `add-local`.
