### ISSUE TITLE
Link error on macOS12.4 on ARM64 (M1)

### ISSUE THREAD

**Issue by JohanEngelen** [CyberShadow/ae#54]
Link output when building `digger` on Apple M1 chip with macOS 12.4:
```
Undefined symbols for architecture arm64:
  "_fdopendir$INODE64", referenced from:
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi1Vbi0ZQwFAyaQdZ9__lambda4Z5Entry7recurseMFZv in digger.o
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi0Vbi0ZQwFAyaQdZ9__lambda4Z5Entry7recurseMFZv in digger.o
  "_fstatat$INODE64", referenced from:
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi1Vbi0ZQwFAyaQdZ9__lambda4Z5Entry__T7tryStatVEQDqQDqQDp__TQDnSQEgQEgQEf__TQDlVbi1Vbi0ZQDxFQDcQDfZQDdZQCw10StatTargeti1ZQDfMFNbNiZb in digger.o
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi1Vbi0ZQwFAyaQdZ9__lambda4Z5Entry__T7tryStatVEQDqQDqQDp__TQDnSQEgQEgQEf__TQDlVbi1Vbi0ZQDxFQDcQDfZQDdZQCw10StatTargeti0ZQDfMFNbNiZb in digger.o
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi0Vbi0ZQwFAyaQdZ9__lambda4Z5Entry__T7tryStatVEQDqQDqQDp__TQDnSQEgQEgQEf__TQDlVbi0Vbi0ZQDxFQDcQDfZQDdZQCw10StatTargeti1ZQDfMFNbNiZb in digger.o
      __D2ae3sys4file__T7listDirSQyQxQv__T11fastListDirVbi0Vbi0ZQwFAyaQdZ9__lambda4Z5Entry__T7tryStatVEQDqQDqQDp__TQDnSQEgQEgQEf__TQDlVbi0Vbi0ZQDxFQDcQDfZQDdZQCw10StatTargeti0ZQDfMFNbNiZb in digger.o
ld: symbol(s) not found for architecture arm64
```

The problem is fixed when simply removing the `pragma(mangle, ...` on the two functions here: https://github.com/CyberShadow/ae/blob/7366be2e75a58dff6a85b6c1af90c9ca541c9373/sys/file.d#L142-L145

**Comment by CyberShadow** [comment]
> The problem is fixed when simply removing the `pragma(mangle, ...` on the two functions here:

Careful, that will fix the link error but will cause it to use incompatible type definitions, possibly leading to memory corruption (at least on the older OSes).

I don't know what the correct fix for 12.4 is.

**Comment by JohanEngelen** [comment]
perhaps it's just missing the correct library to link to?

**Comment by CyberShadow** [comment]
The library is the system libc, but we're using a private interface to it (linking directly to it - the public interface being C header files and the system compiler).

Here's what Druntime does:

https://github.com/dlang/dmd/blob/313cc232abb9ea39c952a62a0191354f1835122c/druntime/src/core/sys/posix/dirent.d#L217-L229

So it looks like it's AArch64 (or rather x86/x86_64) specific, we can do the same:

69df609ce97ca30f2c13ab5bfd7f5762a5a8d449

> Link output when building `digger` on Apple M1 chip with macOS 12.4:

BTW, Digger currently only supports building the DMD compiler, which can only output x86 and x86_64 code. So, you would need to use Rosetta anyhow to be able to use the compiler output, so maybe it would be simpler to just build everything for x86/x86_64.

**Comment by JohanEngelen** [comment]
> So it looks like it's AArch64 (or rather x86/x86_64) specific, we can do the same:
> 
> [69df609](https://github.com/CyberShadow/ae/commit/69df609ce97ca30f2c13ab5bfd7f5762a5a8d449)

This fixes it.
